# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vchevill <vchevill@student.42lyon.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/08 11:25:48 by vchevill          #+#    #+#              #
#    Updated: 2022/02/03 11:46:14 by vchevill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	= ft_isalnum.c ft_isascii.c ft_islower.c ft_isupper.c ft_memset.c ft_bzero.c ft_isalpha.c ft_isdigit.c ft_isprint.c ft_memcpy.c  ft_strlen.c ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_strjoin_free_s1.c

SRCS_BONUS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS	= $(SRCS:.c=.o)

OBJS_BONUS	= $(SRCS_BONUS:.c=.o)

NAME	= libft.a

FLAGS	= -Wall -Wextra -Werror

CC		= gcc

LIB		= ar rcs

RM		= rm -f

all :       $(NAME)

%.o :		%.c libft.h
			gcc $(FLAGS) -c $< -o $@

$(NAME) :	$(OBJS)
			$(LIB) $(NAME) $(OBJS)

bonus :	$(OBJS_BONUS)
			$(LIB) $(NAME) $(OBJS_BONUS)

clean :
			$(RM) $(OBJS) $(OBJS_BONUS)

fclean :	clean
			$(RM) $(NAME)

re :		fclean all

.PHONY :	all, clean, fclean, re 

